version: 2

sources:
  - name: pvibe
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: orders
        columns:
          - name: o_orderkey
            tests:
              - unique
              - not_null
      - name: customer
        
      - name: nation
      - name: region
        
          
            
